import { executeConversionBranchWrites } from '@/lib/transactions/transaction-convert-branch-writes';
import type { ConvertWriteBaseParams } from '@/lib/transactions/transaction-convert-write-types';

export async function executeExpenseConversionWrites({
  tx,
  id,
  userId,
  householdId,
  targetAccountId,
  transaction,
  sourceAccount,
  targetAccount,
  amountCents,
  transferGroupId,
  pairedTransactionId,
  nowIso,
}: ConvertWriteBaseParams): Promise<void> {
  await executeConversionBranchWrites({
    tx,
    id,
    userId,
    householdId,
    amountCents,
    transferGroupId,
    pairedTransactionId,
    nowIso,
    originalTransactionDate: transaction.date,
    originalTransactionNotes: transaction.notes,
    originalTransactionDescription: transaction.description,
    convertedType: 'transfer_out',
    convertedDescription: `Transfer: ${sourceAccount.name} -> ${targetAccount.name}`,
    convertedSourceAccountId: transaction.accountId,
    convertedDestinationAccountId: targetAccountId,
    pairedType: 'transfer_in',
    pairedDescription: `Transfer: ${sourceAccount.name} -> ${targetAccount.name}`,
    pairedAccountId: targetAccountId,
    pairedId: pairedTransactionId,
    pairedLinkTransactionId: id,
    pairedSourceAccountId: transaction.accountId,
    pairedDestinationAccountId: targetAccountId,
    balanceDeltaCents: amountCents,
    canonicalFromAccountId: transaction.accountId,
    canonicalToAccountId: targetAccountId,
    canonicalFromTransactionId: id,
    canonicalToTransactionId: pairedTransactionId,
    isPending: transaction.isPending,
  });
}

export async function executeIncomeConversionWrites({
  tx,
  id,
  userId,
  householdId,
  targetAccountId,
  transaction,
  sourceAccount,
  targetAccount,
  amountCents,
  transferGroupId,
  pairedTransactionId,
  nowIso,
}: ConvertWriteBaseParams): Promise<void> {
  await executeConversionBranchWrites({
    tx,
    id,
    userId,
    householdId,
    amountCents,
    transferGroupId,
    pairedTransactionId,
    nowIso,
    originalTransactionDate: transaction.date,
    originalTransactionNotes: transaction.notes,
    originalTransactionDescription: transaction.description,
    convertedType: 'transfer_in',
    convertedDescription: `Transfer: ${targetAccount.name} -> ${sourceAccount.name}`,
    convertedSourceAccountId: targetAccountId,
    convertedDestinationAccountId: transaction.accountId,
    pairedType: 'transfer_out',
    pairedDescription: `Transfer: ${targetAccount.name} -> ${sourceAccount.name}`,
    pairedAccountId: targetAccountId,
    pairedId: pairedTransactionId,
    pairedLinkTransactionId: id,
    pairedSourceAccountId: targetAccountId,
    pairedDestinationAccountId: transaction.accountId,
    balanceDeltaCents: -amountCents,
    canonicalFromAccountId: targetAccountId,
    canonicalToAccountId: transaction.accountId,
    canonicalFromTransactionId: pairedTransactionId,
    canonicalToTransactionId: id,
    isPending: transaction.isPending,
  });
}
